version: '3.8'

services:
  # --- 1. BASE DE DATOS PILOTO ALFA (PRODUCCIÓN) ---
  db_alfa:
    image: postgis/postgis:15-3.3
    container_name: basurapp_db_alfa
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: basurapp_alfa
      POSTGRES_USER: admin_alfa
      POSTGRES_PASSWORD: "123456"
    volumes:
      - postgres_alfa_data:/var/lib/postgresql/data
    networks:
      - basurapp_network

  # --- 2. BACKEND (SPRING BOOT) ---
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: basurapp_backend
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db_alfa
    environment:
      # Conexión a la base de datos Alfa (Docker reemplaza localhost por db_alfa)
      - DB_URL=jdbc:postgresql://db_alfa:5432/basurapp_alfa
      - DB_USER=admin_alfa
      - DB_PASSWORD=123456
      
      # Variables adicionales de tu sistema
      - JWT_SECRET=clave_secreta_jwt_dev_para_basurapp_2026_utp_chiclayo
      - FIREBASE_ACCOUNT_PATH=classpath:firebase-service-account.json
      - SERVIDOR_RUTAS_URL=http://emulador_rutas:3000

    volumes:
      - ./Backend/FotosReportes:/app/FotosReportes
      - ./Backend/src/main/resources/firebase-service-account.json:/app/config/firebase-service-account.json:ro
    networks:
      - basurapp_network

  # --- 3. EMULADOR / SERVIDOR DE RUTAS ---
  emulador_rutas:
    build:
      context: ./ServidorRutas
      dockerfile: Dockerfile
    container_name: basurapp_emulador
    restart: always
    ports:
      - "3003:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8080
    networks:
      - basurapp_network

volumes:
  postgres_alfa_data:
  postgres_dev_data:

networks:
  basurapp_network:
    driver: bridge